import type {
  Member,
  Rounding,
  Transaction,
  MemberFeeRecord,
  PlayerRoundScore,
} from "@/types";

// ─── Members ──────────────────────────────────────────────────────────────────

export const MOCK_MEMBERS: Member[] = [
  {
    id: "m1",
    name: "김태준",
    department: "전략기획팀",
    position: "부장",
    phone: "010-1234-5678",
    email: "taejun.kim@company.com",
    handicap: 8,
    joinedAt: "2021-03-15",
    status: "active",
    avatarInitials: "김태",
  },
  {
    id: "m2",
    name: "박지현",
    department: "영업1팀",
    position: "차장",
    phone: "010-2345-6789",
    email: "jihyun.park@company.com",
    handicap: 12,
    joinedAt: "2021-05-20",
    status: "active",
    avatarInitials: "박지",
  },
  {
    id: "m3",
    name: "이승민",
    department: "개발팀",
    position: "과장",
    phone: "010-3456-7890",
    email: "seungmin.lee@company.com",
    handicap: 18,
    joinedAt: "2022-01-10",
    status: "active",
    avatarInitials: "이승",
  },
  {
    id: "m4",
    name: "최수연",
    department: "마케팅팀",
    position: "대리",
    phone: "010-4567-8901",
    email: "suyeon.choi@company.com",
    handicap: 22,
    joinedAt: "2022-06-01",
    status: "active",
    avatarInitials: "최수",
  },
  {
    id: "m5",
    name: "정우성",
    department: "재무팀",
    position: "부장",
    phone: "010-5678-9012",
    email: "woosung.jung@company.com",
    handicap: 6,
    joinedAt: "2020-09-01",
    status: "active",
    avatarInitials: "정우",
  },
  {
    id: "m6",
    name: "한미영",
    department: "인사팀",
    position: "차장",
    phone: "010-6789-0123",
    email: "miyoung.han@company.com",
    handicap: 15,
    joinedAt: "2021-11-15",
    status: "active",
    avatarInitials: "한미",
  },
  {
    id: "m7",
    name: "오준혁",
    department: "영업2팀",
    position: "과장",
    phone: "010-7890-1234",
    email: "junhyeok.oh@company.com",
    handicap: 20,
    joinedAt: "2022-03-22",
    status: "active",
    avatarInitials: "오준",
  },
  {
    id: "m8",
    name: "윤서아",
    department: "개발팀",
    position: "사원",
    phone: "010-8901-2345",
    email: "seoa.yoon@company.com",
    handicap: 28,
    joinedAt: "2023-02-14",
    status: "active",
    avatarInitials: "윤서",
  },
  {
    id: "m9",
    name: "강민준",
    department: "전략기획팀",
    position: "과장",
    phone: "010-9012-3456",
    email: "minjun.kang@company.com",
    handicap: 10,
    joinedAt: "2021-07-30",
    status: "active",
    avatarInitials: "강민",
  },
  {
    id: "m10",
    name: "임채원",
    department: "마케팅팀",
    position: "차장",
    phone: "010-0123-4567",
    email: "chaewon.lim@company.com",
    handicap: 14,
    joinedAt: "2021-09-05",
    status: "active",
    avatarInitials: "임채",
  },
  {
    id: "m11",
    name: "신동현",
    department: "재무팀",
    position: "대리",
    phone: "010-1111-2222",
    email: "donghyun.shin@company.com",
    handicap: 24,
    joinedAt: "2023-05-10",
    status: "pending",
    avatarInitials: "신동",
  },
  {
    id: "m12",
    name: "배지원",
    department: "영업1팀",
    position: "사원",
    phone: "010-2222-3333",
    email: "jiwon.bae@company.com",
    handicap: 30,
    joinedAt: "2023-08-20",
    status: "inactive",
    avatarInitials: "배지",
  },
];

// ─── Roundings ────────────────────────────────────────────────────────────────

export const MOCK_ROUNDINGS: Rounding[] = [
  {
    id: "r1",
    title: "6월 정기 라운딩",
    courseId: "c1",
    courseName: "남서울 컨트리클럽",
    date: "2026-06-28",
    teeTime: "07:30",
    maxParticipants: 12,
    fee: 150000,
    status: "scheduled",
    attendances: [
      { memberId: "m1", status: "attending", registeredAt: "2026-06-01T09:00:00" },
      { memberId: "m2", status: "attending", registeredAt: "2026-06-01T10:30:00" },
      { memberId: "m3", status: "attending", registeredAt: "2026-06-02T08:00:00" },
      { memberId: "m4", status: "attending", registeredAt: "2026-06-02T14:00:00" },
      { memberId: "m5", status: "attending", registeredAt: "2026-06-03T09:00:00" },
      { memberId: "m6", status: "attending", registeredAt: "2026-06-03T11:00:00" },
      { memberId: "m7", status: "attending", registeredAt: "2026-06-04T09:00:00" },
      { memberId: "m8", status: "attending", registeredAt: "2026-06-04T13:00:00" },
      { memberId: "m9", status: "waitlist", registeredAt: "2026-06-05T09:00:00" },
      { memberId: "m10", status: "absent", registeredAt: "2026-06-05T10:00:00" },
    ],
  },
  {
    id: "r2",
    title: "5월 정기 라운딩",
    courseId: "c2",
    courseName: "레이크사이드 CC",
    date: "2026-05-25",
    teeTime: "08:00",
    maxParticipants: 8,
    fee: 130000,
    status: "completed",
    attendances: [
      { memberId: "m1", status: "attending", registeredAt: "2026-05-01T09:00:00" },
      { memberId: "m2", status: "attending", registeredAt: "2026-05-02T10:00:00" },
      { memberId: "m5", status: "attending", registeredAt: "2026-05-03T09:00:00" },
      { memberId: "m6", status: "attending", registeredAt: "2026-05-04T11:00:00" },
      { memberId: "m9", status: "attending", registeredAt: "2026-05-05T09:00:00" },
      { memberId: "m10", status: "attending", registeredAt: "2026-05-06T10:00:00" },
      { memberId: "m3", status: "attending", registeredAt: "2026-05-07T09:00:00" },
      { memberId: "m4", status: "attending", registeredAt: "2026-05-08T14:00:00" },
    ],
    groups: [
      {
        id: "g1",
        label: "1조",
        members: [
          { id: "m5", name: "정우성", department: "재무팀", handicap: 6, avatarInitials: "정우" },
          { id: "m10", name: "임채원", department: "마케팅팀", handicap: 14, avatarInitials: "임채" },
          { id: "m4", name: "최수연", department: "마케팅팀", handicap: 22, avatarInitials: "최수" },
        ],
      },
      {
        id: "g2",
        label: "2조",
        members: [
          { id: "m1", name: "김태준", department: "전략기획팀", handicap: 8, avatarInitials: "김태" },
          { id: "m6", name: "한미영", department: "인사팀", handicap: 15, avatarInitials: "한미" },
          { id: "m3", name: "이승민", department: "개발팀", handicap: 18, avatarInitials: "이승" },
        ],
      },
      {
        id: "g3",
        label: "3조",
        members: [
          { id: "m9", name: "강민준", department: "전략기획팀", handicap: 10, avatarInitials: "강민" },
          { id: "m2", name: "박지현", department: "영업1팀", handicap: 12, avatarInitials: "박지" },
          { id: "m7", name: "오준혁", department: "영업2팀", handicap: 20, avatarInitials: "오준" },
        ],
      },
    ],
  },
  {
    id: "r3",
    title: "7월 번개 라운딩",
    courseId: "c3",
    courseName: "블루원 용인 CC",
    date: "2026-07-12",
    teeTime: "06:30",
    maxParticipants: 16,
    fee: 160000,
    status: "scheduled",
    attendances: [
      { memberId: "m1", status: "attending", registeredAt: "2026-06-10T09:00:00" },
      { memberId: "m3", status: "attending", registeredAt: "2026-06-10T10:00:00" },
      { memberId: "m5", status: "attending", registeredAt: "2026-06-11T09:00:00" },
    ],
  },
];

// ─── Transactions ─────────────────────────────────────────────────────────────

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: "t1",
    date: "2026-06-05",
    description: "6월 정기 회비 - 김태준",
    type: "income",
    feeType: "monthly_fee",
    amount: 30000,
    memberId: "m1",
    balance: 2480000,
  },
  {
    id: "t2",
    date: "2026-06-05",
    description: "6월 정기 회비 - 박지현",
    type: "income",
    feeType: "monthly_fee",
    amount: 30000,
    memberId: "m2",
    balance: 2510000,
  },
  {
    id: "t3",
    date: "2026-06-05",
    description: "6월 정기 회비 - 이승민",
    type: "income",
    feeType: "monthly_fee",
    amount: 30000,
    memberId: "m3",
    balance: 2540000,
  },
  {
    id: "t4",
    date: "2026-06-10",
    description: "5월 라운딩 참가비 - 김태준",
    type: "income",
    feeType: "other",
    amount: 130000,
    memberId: "m1",
    roundingId: "r2",
    balance: 2670000,
  },
  {
    id: "t5",
    date: "2026-06-10",
    description: "5월 라운딩 참가비 - 박지현",
    type: "income",
    feeType: "other",
    amount: 130000,
    memberId: "m2",
    roundingId: "r2",
    balance: 2800000,
  },
  {
    id: "t6",
    date: "2026-06-15",
    description: "골프공 구매 (동호회 공용)",
    type: "expense",
    feeType: "other",
    amount: 80000,
    balance: 2720000,
  },
  {
    id: "t7",
    date: "2026-06-20",
    description: "6월 정기 회비 - 정우성",
    type: "income",
    feeType: "monthly_fee",
    amount: 30000,
    memberId: "m5",
    balance: 2750000,
  },
  {
    id: "t8",
    date: "2026-06-20",
    description: "6월 정기 회비 - 한미영",
    type: "income",
    feeType: "monthly_fee",
    amount: 30000,
    memberId: "m6",
    balance: 2780000,
  },
  {
    id: "t9",
    date: "2026-06-22",
    description: "라운딩 시상품 구매",
    type: "expense",
    feeType: "club_expense",
    amount: 120000,
    roundingId: "r1",
    balance: 2660000,
  },
  {
    id: "t10",
    date: "2026-06-22",
    description: "5월 라운딩 참가비 - 정우성",
    type: "income",
    feeType: "other",
    amount: 130000,
    memberId: "m5",
    roundingId: "r2",
    balance: 2790000,
  },
];

// ─── Member Fee Records ───────────────────────────────────────────────────────

export const MOCK_FEE_RECORDS: MemberFeeRecord[] = MOCK_MEMBERS.filter(
  (m) => m.status !== "inactive"
).map((member) => ({
  memberId: member.id,
  memberName: member.name,
  year: 2026,
  month: 6,
  monthlyFee: (["m1", "m2", "m3", "m5", "m6"].includes(member.id) ? "paid" : "unpaid") as "paid" | "unpaid",
  roundingFees: [
    {
      roundingId: "r2",
      roundingTitle: "5월 정기 라운딩",
      amount: 130000,
      status: (["m1", "m2", "m5", "m9", "m10"].includes(member.id)
        ? "paid"
        : "unpaid") as "paid" | "unpaid",
    },
  ],
}));

// ─── Leaderboard (completed round scores) ────────────────────────────────────

export const MOCK_SCORES: PlayerRoundScore[] = [
  {
    memberId: "m1",
    memberName: "김태준",
    grossScore: 84,
    holeScores: [
      { hole: 1, par: 4, score: 5 },
      { hole: 2, par: 3, score: 4 },
      { hole: 3, par: 5, score: 6 },
      { hole: 4, par: 4, score: 4 },
      { hole: 5, par: 4, score: 5 },
      { hole: 6, par: 3, score: 3 },
      { hole: 7, par: 5, score: 6 },
      { hole: 8, par: 4, score: 5 },
      { hole: 9, par: 4, score: 4 },
      { hole: 10, par: 4, score: 5 },
      { hole: 11, par: 3, score: 4 },
      { hole: 12, par: 5, score: 6 },
      { hole: 13, par: 4, score: 4 },
      { hole: 14, par: 4, score: 5 },
      { hole: 15, par: 3, score: 3 },
      { hole: 16, par: 5, score: 6 },
      { hole: 17, par: 4, score: 5 },
      { hole: 18, par: 4, score: 4 },
    ],
    shinPerioHandicap: 11.2,
    netScore: 73,
    rank: 1,
  },
  {
    memberId: "m5",
    memberName: "정우성",
    grossScore: 80,
    holeScores: [
      { hole: 1, par: 4, score: 4 },
      { hole: 2, par: 3, score: 3 },
      { hole: 3, par: 5, score: 6 },
      { hole: 4, par: 4, score: 5 },
      { hole: 5, par: 4, score: 4 },
      { hole: 6, par: 3, score: 4 },
      { hole: 7, par: 5, score: 5 },
      { hole: 8, par: 4, score: 4 },
      { hole: 9, par: 4, score: 5 },
      { hole: 10, par: 4, score: 4 },
      { hole: 11, par: 3, score: 3 },
      { hole: 12, par: 5, score: 6 },
      { hole: 13, par: 4, score: 5 },
      { hole: 14, par: 4, score: 4 },
      { hole: 15, par: 3, score: 4 },
      { hole: 16, par: 5, score: 5 },
      { hole: 17, par: 4, score: 4 },
      { hole: 18, par: 4, score: 5 },
    ],
    shinPerioHandicap: 8.0,
    netScore: 72,
    rank: 2,
  },
  {
    memberId: "m9",
    memberName: "강민준",
    grossScore: 88,
    holeScores: [
      { hole: 1, par: 4, score: 5 },
      { hole: 2, par: 3, score: 4 },
      { hole: 3, par: 5, score: 7 },
      { hole: 4, par: 4, score: 5 },
      { hole: 5, par: 4, score: 5 },
      { hole: 6, par: 3, score: 4 },
      { hole: 7, par: 5, score: 6 },
      { hole: 8, par: 4, score: 5 },
      { hole: 9, par: 4, score: 5 },
      { hole: 10, par: 4, score: 5 },
      { hole: 11, par: 3, score: 4 },
      { hole: 12, par: 5, score: 6 },
      { hole: 13, par: 4, score: 5 },
      { hole: 14, par: 4, score: 5 },
      { hole: 15, par: 3, score: 4 },
      { hole: 16, par: 5, score: 7 },
      { hole: 17, par: 4, score: 5 },
      { hole: 18, par: 4, score: 5 },
    ],
    shinPerioHandicap: 14.4,
    netScore: 74,
    rank: 3,
  },
];

// ─── Finance Stats ────────────────────────────────────────────────────────────

export const MOCK_MONTHLY_STATS = [
  { month: "1월", income: 380000, expense: 50000 },
  { month: "2월", income: 360000, expense: 120000 },
  { month: "3월", income: 420000, expense: 200000 },
  { month: "4월", income: 390000, expense: 80000 },
  { month: "5월", income: 580000, expense: 300000 },
  { month: "6월", income: 480000, expense: 200000 },
];

export const CURRENT_BALANCE = 2790000;
